name: Lotto Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create Firebase key file
        run: |
          echo '${{ secrets.FIREBASE_KEY }}' > firebase_key.json

      - name: Debug file
        run: ls -la

      - name: Run scraper
        run: python scraper.py
